<?php

namespace Container3df45uC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetTweetConverterUseCaseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Application\UseCase\GetTweetConverterUseCase' shared autowired service.
     *
     * @return \App\Application\UseCase\GetTweetConverterUseCase
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/UseCase/GetTweetConverterUseCase.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Service/ChangeTweetsToUpperCaseService.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Repository/TweetRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Repository/TweetRepositoryInMemory.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Service/AssertUserNameHasValidFormatService.php';

        return $container->privates['App\\Application\\UseCase\\GetTweetConverterUseCase'] = new \App\Application\UseCase\GetTweetConverterUseCase(new \App\Domain\Service\ChangeTweetsToUpperCaseService(new \App\Infrastructure\Repository\TweetRepositoryInMemory(), new \App\Domain\Service\AssertUserNameHasValidFormatService()));
    }
}
