<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQUvti41\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQUvti41/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQUvti41.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQUvti41\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQUvti41\App_KernelDevDebugContainer([
    'container.build_hash' => 'QUvti41',
    'container.build_id' => '0cfbbfda',
    'container.build_time' => 1699814794,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQUvti41');
