<?php

namespace ContainerQUvti41;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N6jtsbFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N6jtsbF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N6jtsbF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'useCase' => ['privates', 'App\\Application\\UseCase\\GetTweetConverterUseCase', 'getGetTweetConverterUseCaseService', true],
            'validator' => ['services', '.container.private.validator', 'get_Container_Private_ValidatorService', true],
        ], [
            'useCase' => 'App\\Application\\UseCase\\GetTweetConverterUseCase',
            'validator' => '?',
        ]);
    }
}
